# Generated by Django 2.2.2 on 2019-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_images',
            field=models.FilePathField(null=True, path='img/'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.FilePathField(null=True, path='img/'),
        ),
    ]
