# Generated by Django 2.2.2 on 2019-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190626_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='full_description_images',
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.FileField(null=True, upload_to='static/img/'),
        ),
    ]
