# Generated by Django 2.2.2 on 2019-06-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190626_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.FileField(null=True, upload_to='portfolio/static/img/'),
        ),
    ]
