# Generated by Django 2.2.2 on 2019-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190626_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_description_images',
            field=models.FilePathField(null=True, path='img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.FilePathField(null=True, path='img/'),
        ),
    ]
