# Generated by Django 2.2.2 on 2019-06-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_delete_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='annotation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header2',
            field=models.TextField(null=True),
        ),
    ]
