# Generated by Django 2.2.2 on 2019-06-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_homepage_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='main_header',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='secondary_header',
        ),
    ]
