# Generated by Django 2.2.2 on 2019-06-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_image'),
        ('portfolio', '0008_auto_20190627_1012'),
        ('homepage', '0013_auto_20190628_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='portfolio.Project'),
        ),
    ]
