# Generated by Django 2.2.2 on 2019-07-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_myflatpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFlatPage',
        ),
    ]
