# Generated by Django 2.2.2 on 2019-07-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('homepage', '0016_delete_myflatpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('header', models.CharField(max_length=200, verbose_name='header')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
