# Generated by Django 2.2.2 on 2019-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20190701_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflatpage',
            name='main_header',
        ),
        migrations.RemoveField(
            model_name='myflatpage',
            name='secondary_header',
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='header1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='header2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
