# Generated by Django 2.2.2 on 2019-07-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20190701_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFlatPage',
        ),
    ]
