# Generated by Django 2.2.2 on 2019-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_newflatpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newflatpage',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Основной текстовый контент страницы'),
        ),
        migrations.AlterField(
            model_name='newflatpage',
            name='text_block',
            field=models.CharField(default='', max_length=200, verbose_name='Дополнительный блок текста'),
        ),
    ]
