# Generated by Django 2.2.2 on 2019-07-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_auto_20190701_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewFlatpage',
        ),
    ]
