# Generated by Django 2.2.2 on 2019-07-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_extendedflatpage_myflatpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflatpage',
            name='header',
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='header1',
            field=models.CharField(default='', max_length=200, verbose_name='header1'),
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='header2',
            field=models.CharField(default='', max_length=200, verbose_name='header2'),
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='text_field',
            field=models.CharField(default='', max_length=200, verbose_name='text_field'),
        ),
    ]
