# Generated by Django 2.2.2 on 2019-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_auto_20190701_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflatpage',
            name='content1',
            field=models.TextField(default='', verbose_name='content1'),
        ),
        migrations.AlterField(
            model_name='myflatpage',
            name='content2',
            field=models.TextField(default='', verbose_name='content2'),
        ),
        migrations.AlterField(
            model_name='myflatpage',
            name='content3',
            field=models.TextField(default='', verbose_name='content3'),
        ),
    ]
