# Generated by Django 2.2.3 on 2019-07-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='comments',
        ),
    ]
