# Generated by Django 2.2.3 on 2019-07-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190705_0039'),
        ('blog', '0012_auto_20190705_1546'),
    ]

    operations = [
    ]
