# Generated by Django 2.2.2 on 2019-06-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190627_1012'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Category'),
        ),
        migrations.AddField(
            model_name='home',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Project'),
        ),
    ]
