# Generated by Django 2.2.2 on 2019-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190627_1012'),
        ('homepage', '0002_auto_20190627_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='categories',
        ),
        migrations.AddField(
            model_name='home',
            name='categories',
            field=models.ManyToManyField(to='portfolio.Category'),
        ),
        migrations.RemoveField(
            model_name='home',
            name='projects',
        ),
        migrations.AddField(
            model_name='home',
            name='projects',
            field=models.ManyToManyField(to='portfolio.Project'),
        ),
    ]
