# Generated by Django 2.2.2 on 2019-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190627_1012'),
        ('homepage', '0004_auto_20190627_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=200)),
                ('civil_projects', models.ManyToManyField(related_name='civil_projects', to='portfolio.Project')),
                ('software_projects', models.ManyToManyField(related_name='software_projects', to='portfolio.Project')),
            ],
        ),
    ]
