# Generated by Django 2.2.2 on 2019-06-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='civil_projects',
        ),
    ]
