# Generated by Django 2.2.2 on 2019-06-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20190627_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
