# Generated by Django 2.2.2 on 2019-06-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_image'),
        ('homepage', '0010_auto_20190628_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='blog.Post'),
        ),
    ]
