# Generated by Django 2.2.2 on 2019-06-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20190628_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='projects',
        ),
    ]
