# Generated by Django 2.2.2 on 2019-07-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_myflatpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflatpage',
            name='header',
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='main_header',
            field=models.CharField(max_length=200, null=True, verbose_name='main_header'),
        ),
        migrations.AddField(
            model_name='myflatpage',
            name='secondary_header',
            field=models.CharField(max_length=200, null=True, verbose_name='secondary_header'),
        ),
    ]
