# Generated by Django 2.2.2 on 2019-07-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_auto_20190701_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedFlatPage',
        ),
    ]
