# Generated by Django 2.2.3 on 2019-07-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_delete_extendedflatpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='story',
            field=models.TextField(default=''),
        ),
    ]
