# Generated by Django 2.2.2 on 2019-06-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190626_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='full_description_images',
            field=models.FilePathField(null=True, path='portfolio/img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.FilePathField(null=True, path='portfolio/img/'),
        ),
    ]
