# Generated by Django 2.2.2 on 2019-06-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190627_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='full_description_images',
        ),
    ]
