# Generated by Django 2.2.3 on 2019-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20190705_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='images/portfolio/'),
        ),
    ]
