# Generated by Django 2.2.3 on 2019-07-11 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20190711_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='portfolio.Project'),
        ),
    ]
