# Generated by Django 2.2.3 on 2019-07-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20190711_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimages',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True),
        ),
    ]
