# Generated by Django 2.2.3 on 2019-07-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20190715_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_description_2',
            field=models.TextField(blank=True, default=''),
        ),
    ]
