# Generated by Django 2.2.2 on 2019-07-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190630_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
